# Generated by Django 4.2.29 on 2026-03-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_genre_description_alter_genre_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('duration', models.IntegerField(max_length=100)),
            ],
        ),
    ]
