# Generated by Django 4.2.29 on 2026-03-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_track_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name_en',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name_ru',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
